const DEFAULT_API_BASE_URL = 'http://localhost:8080/api';
const GIF_VIDEO_BASE_ENDPOINT = "/gif";
const GIF_VIDEO_UPLOAD_ENDPOINT = "/gif/upload";
const GIF_VIDEO_URL_ENDPOINT = "/gif/url";
const GIF_DOWNLOAD_ENDPOINT = "/gif/download/{transactionId}";
const BASE_URL = process.env.VIDEO_PROCESSOR_BASE_URL || DEFAULT_API_BASE_URL;

export const ApiConfig = {
    BASE_URL: BASE_URL,
    GIF_VIDEO_BASE_ENDPOINT: GIF_VIDEO_BASE_ENDPOINT,
    GIF_VIDEO_UPLOAD_ENDPOINT: GIF_VIDEO_UPLOAD_ENDPOINT,
    GIF_VIDEO_URL_ENDPOINT: GIF_VIDEO_URL_ENDPOINT,
    GIF_DOWNLOAD_ENDPOINT: GIF_DOWNLOAD_ENDPOINT,
    GIF_DOWNLOAD_URL: BASE_URL + GIF_DOWNLOAD_ENDPOINT,
    START_END_TIME_RANGE: Number(process.env.START_END_TIME_RANGE || 60),
};

export const GifVideoStatus = {
    IN_PROGRESS: 'IN_PROGRESS',
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
}